name: "PR Required Tasks Validator"
description: "Validates that all required tasks in pull request checklists are completed, with support for marking tasks and sections as optional"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
